LOAD DATA
INFILE 'C:\Users\Jose Orlando\SDS_LOCALIDADES_LCD_DATA_TABLE.ldr' "str '\r\n'"
CONTINUEIF NEXT(1:1) = '#'
INTO TABLE "PRUEBAS"."SDS_LOCALIDADES_LCD"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' AND '"'
TRAILING NULLCOLS ( 
"LCD_CODIGO" ,
"CTR_ANO_FISCAL" ,
"CTR_ID_CENTRO" ,
"PSO_CODIGO" ,
"EDO_CODIGO" ,
"LCD_NOMBRE" )
